services:
  dataforge-ui:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dataforge-ui.rule=Host(`dataforge.markets`)"
      - "traefik.http.routers.dataforge-ui.entrypoints=https"
      - "traefik.http.routers.dataforge-ui.tls=true"
      - "traefik.http.routers.dataforge-ui.tls.certresolver=forge"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true
